### ISSUE TITLE
Empty results message is displayed on homepage

### ISSUE THREAD

**Issue by jayaddison** [openculinary/frontend#230]
**Describe the bug**
Currently there is a default empty-results message appearing on the homepage below the search controls.

It may be possible to use the `formatNoMatches` option to `bootstrap-table` to adjust the message and/or hide it.  Or, alternatively, perhaps we should hide an element that contains it using `jQuery` and only show it when a search is performed by the user.

**To Reproduce**
1. Visit the homepage (without any search parameters or arguments in the URL).
2. The empty-results message appears below the search controls.

**Expected behavior**
The area below the search controls (apart from the page footer) should be blank during homepage visits.

**Screenshots**
![image](https://github.com/openculinary/frontend/assets/55152140/2ee1d21d-18d7-4366-a24e-01ab57448952)

**Comment by jayaddison** [comment]
This appears to have been caused by commit 28cc26b6b3c5009db73b0cf6a4c0761198b3df7d that was introduced earlier today; let's revert that and then figure out how to proceed.

(it was introduced in order to get unit tests running again locally -- compilation errors were occuring when building the tests -- but appears to have had other side-effects)
